name: Check OBS Build

on:
  schedule:
    - cron: '0 0 * * 1-5'
  issue_comment:
    types: [created]
jobs:
  package_status_check:
    name: Check package build status on OBS
    runs-on: ubuntu-latest
    steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
      - name: Install python3
        uses: actions/setup-python@v2
      - name: Install requirement
        run: |
          sudo apt install python3-pip git
          pip install requests pyyaml xmltodict markdown pymdown-extensions
      - name: Run the script
        if: ${{ contains(github.event.comment.body, 'recheck_official') || contains(github.event.comment.body, 'recheck_test') || github.event_name == 'schedule' }}
        run: |
          git clone https://gitee.com/openeuler/openstack
          cd openstack/tools/oos
          pip install -r requirement.txt
          pip install -e .
          cd scripts
          export OBS_USER_NAME=${{ secrets.obs_user_name }}
          export OBS_USER_PASSWORD=${{ secrets.obs_user_password }}
          export GITEE_USER_TOKEN=${{ secrets.gitee_user_token }}
          python3 ./check_obs_status.py html
          pwd
      - name: Send email to SIG
        if: ${{ contains(github.event.comment.body, 'recheck_official') || github.event_name == 'schedule' }}
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          # Required mail server address:
          server_address: smtp.qq.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: OpenStack OBS Daily Check
          # Required recipients' addresses:
          to: wangxiyuan@huawei.com,huangtianhua@huawei.com,lijiawei19@huawei.com
          # Required sender full name (address can be skipped):
          from: OpenStack CI Boot # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          html_body: file://home/runner/work/openeuler_openstack_action/openeuler_openstack_action/openstack/tools/oos/scripts/result_body.html
          attachments: /home/runner/work/openeuler_openstack_action/openeuler_openstack_action/openstack/tools/oos/scripts/result_attach.html
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
      - name: Send email for Debug
        if: ${{ contains(github.event.comment.body, 'recheck_test') }}
        uses: dawidd6/action-send-mail@v3.6.0
        with:
          # Required mail server address:
          server_address: smtp.qq.com
          # Required mail server port:
          server_port: 465
          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: OpenStack OBS Daily Check
          # Required recipients' addresses:
          to: wangxiyuan@huawei.com
          # Required sender full name (address can be skipped):
          from: OpenStack CI Boot # <user@example.com>
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          html_body: file://result_body.html
          attachments: result_attach.html
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: normal
